version: "3"

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-434104/image-registry/client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    # volumes:
    #   - ./client-gateway/src:/usr/src/app/src
    # command: npm run start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  products-microservice:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-434104/image-registry/products-microservice
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-microservice:
    build:
      context: ./orders-microservice
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-434104/image-registry/orders-microservice
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  # # ===================
  # # PAYMENT MICROSERVICE
  # # ===================
  payments-microservice:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-434104/image-registry/payments-microservice
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - CANCEL_URL=${STRIPE_CANCEL_URL}

  # # ===================
  # # AUTH MICROSERVICE
  # # ===================
  auth-microservice:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: northamerica-northeast1-docker.pkg.dev/tienda-microservice-434104/image-registry/auth-microservice
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
